### ISSUE TITLE
Install Geonetwork 3.2.1 version for testing purpose

### ISSUE THREAD

**Issue by valegrajales** [PEM-Humboldt/core-geonetwork#1]
Install Geonetwork version 3.2.1 for testing purpose in a local machine. The objective is to check if this versions fixes the problems and issues related with the latest installed version on Humboldt infrastructure.

**Comment by valegrajales** [comment]
Acceptance requirements: Small document with the conclusion related to the type of problems that the new version corrects compared to the previous version.

**Comment by rbastidas** [comment]
Se instala GeoNetwork v3.2.1 en una VM local con una base de datos PostgreSQL  9.5.6, se comienza el diagnostico de la aplicación. La aplicación puede ser accedida desde:
http://192.168.205.7:4000/geonetwork/

**Comment by rbastidas** [comment]
Al revisar GeoNetwork v3.2.1 se tiene:
Panel de control:

**Metadatos y plantillas**
Se encuentran los estándares disponibles: 
a. Geographic information -- Metadata (iso19139)
b. Dublin core (dublin-core)
c. Dublin core (for CSW only) (csw-record)
d. Geographic information -- Methodology for feature cataloguing (iso19110)
Adicionalmente, se pueden cargar plantillas y datos de ejemplo. En esta sección también se pueden crear nuevas plantillas de metadatos
**Harvesting**
Proceso de recopilar recursos remotos y almacenarlos localmente para una búsqueda más rápida. Los datos locales y los remotos se mantienen sincronizados por medio de un proceso programado.  
**Estadísticas y estados**
Las estadísticas se muestras de una manera más amigable al usuario permitiendo hacer un despliegue intuitivo de las mismas.
Se tienen estadísticas por:
o	Resultados por categoría
o	Por dueño
o	Por grupo
o	Estado actual del workflow - flujo de trabajo
o	Por estado de validación
o	Metadatos, plantillas o entradas del directorio 
o	Por estándar
En este apartado se encuentra información acerca del catalogo y la ubicación de algunos archivos clave de configuración

**Informes (Nuevo)**
o	Informe de metadato actualizado
Este informe permite extraer una lista de entradas actualizadas y de la información de su autor para un rango de fechas específicos. Esto permitirá asegurar que las entradas están actualizadas y que no es necesario borrar entradas antiguas o caducadas. Estos informes se pueden importar a MS Access y Excel.
o	Informe interno de metadatos
Selecciona un criterio para extraer una lista de entradas internas y la información del dueño de la entrada. Esto permitirá revisar la entrada para asegurar la completitud o si es necesario borrar entradas "vacías" o "pruebas". El informe se podrá importar en MS Access o Excel.
o	Informe de cargas de ficheros
Selecciona un criterio para extraer el histórico de cargas de datos. El informe resultante se puede importar en MS Access y Excel.

o	Informe de descargas de fichero de metadatos
Selecciona un criterio para extraer los datos de un historial de descargas. El informe resultante puede ser importado en MS Access y Excel.

o	Informe de acceso de usuarios
Selecciona el criterio para extraer una lista de nombres de usuario, correos y la fecha del último login. El informe se podrá importar a MS Access y Excel.

**Sistemas de clasificación**
Se encuentra el Tesauros y la definición de alguna nueva categoría para clasificar un conjunto de datos
**Estándares**
Se muestran los Namespace de los estándares utilizados:
iso19139
iso19139-help
Namespace
http://www.isotc211.org/2005/gss
http://www.isotc211.org/2005/gco
http://www.isotc211.org/2005/gmx
http://www.isotc211.org/2005/srv
http://www.opengis.net/gml
http://www.isotc211.org/2005/gts
http://www.isotc211.org/2005/gmd
http://www.w3.org/1999/xlink
Dublin Core
El estándar de metadato Dublin Core
Namespace
http://purl.org/dc/dcmitype/
http://purl.org/dc/terms/
http://www.w3.org/XML/1998/namespace
http://purl.org/dc/elements/1.1/
Dublin Core - CSW
Entradas de metadato producidas por servicios CSW
Namespace
http://purl.org/dc/terms/
http://www.opengis.net/cat/csw/2.0.2
http://www.opengis.net/ows
http://purl.org/dc/elements/1.1/
http://www.w3.org/1999/xlink
iso19110
iso19110-help
Namespace
http://www.isotc211.org/2005/gss
http://www.isotc211.org/2005/gco
http://www.isotc211.org/2005/gmx
http://www.isotc211.org/2005/gfc
http://www.opengis.net/gml
http://www.isotc211.org/2005/gts
http://www.isotc211.org/2005/gmd
http://www.w3.org/1999/xlink

**Usuarios y grupos**: Gestión de usuarios y grupos
**Configuración**: configuración del catalogo
**Herramientas**: Administrador de Índices
Reconstruir índice
Optimizar índice
Recargar la configuración del índice
Limpiar la caché XLink
Limpiar caché JS & CSS
Borrar la Cache del Formateador

En esta versión se pueden visualizar capas geográficas en el visor en un despliegue en 3D.
Se incluyen capas base para el despliegue de información en el visor (OpenStreetMap, Bing Aerial, Stamen Watercolor, Stamen Toner).
El Feedback por parte del usuario es habilitado en esta versión.
La implementación de esta nueva versión requerirá la creación o adaptación de las hojas de estilo de la versión de GeoNetwork que se encuentra en producción. Adicionalmente, se tiene que pensar en la actualización de todos los manuales y lineamientos para la incorporación de información al catalogador de datos geográficos.
