### ISSUE TITLE
Transferir datos en BD postgrest antigua a geonetwork de prueba

### ISSUE THREAD

**Issue by valegrajales** [PEM-Humboldt/core-geonetwork#2]
Hacer dump de la base de datos con los datos de geonetwork en producción y transferirlos a geonetwork de prueba.

**Comment by valegrajales** [comment]
Criterio de aceptación: datos almacenados en BD de nuevo geonetwork con reporte de fallas en la importación.

**Comment by rbastidas** [comment]
Se ha realizado Backup de la Base de datos:
pg_dump --host localhost --port 5432 --username "geonetwork" --verbose --file "/home/cbeltran/BK_20170408_Geonetwork.sql" "geonetwork"

**Comment by rbastidas** [comment]
Se comparan los dos esquemas de bases de datos:
Base de datos Producción: 34 Tablas
![geoproduccion](https://cloud.githubusercontent.com/assets/20953731/25289078/d0da8546-268d-11e7-8d7f-652935566d32.png)

Base de datos Desarrollo: 50 tablas
![geodevelopment](https://cloud.githubusercontent.com/assets/20953731/25289102/e8c320dc-268d-11e7-96cf-79820fe85266.png)

Acciones realizadas:
Backup:
pg_dump --host localhost --port 5432 --username "geonetwork" -Fc geonetwork --verbose > /home/cbeltran/BK_20170418.dump

Actualización de permisos al rol geonetwork:
psql template1
alter role geonetwork with superuser;

Creación de base de datos en ambiente de desarrollo
create database geonetwork with owner geonetwork;

Restauración del Backup
pg_restore -U geonetwork -d geonetwork -p 5432 -h localhost < /media/sf_Geonetwork/BK_20170418.dump

La migración se logra con éxito y se suministra el link de acceso para evaluar el correcto funcionamiento de la aplicación: http://192.168.205.3:4000/geonetwork/srv/spa/catalog.search#/home
