### ISSUE TITLE
Transferir datos no asociados a BD a nuevo geonetwork

### ISSUE THREAD

**Issue by valegrajales** [PEM-Humboldt/core-geonetwork#3]
Transferir los datos estáticos y metadatos en carpetas y archivos desde la versión antigua de geonetwork a la nueva versión de prueba.

**Comment by valegrajales** [comment]
Criterio de aceptación: Datos almacenados en nuevo geonetwork y reporte de errores que se presentan con la transición.

**Comment by rbastidas** [comment]
Se monta la carpeta /data/metadata_data del Backup de Geonetwork Producción a la carpeta de datos de la aplicación en entorno de desarrollo. Al Tratar de descargar los datos desde la nueva versión , la aplicación re direcciona a http://geonetwork.humboldt.org.co el cual es el dominio de la aplicación en producción.
