### ISSUE TITLE
Revisión por pares funcionamiento Geonetwork 3.2.1

### ISSUE THREAD

**Issue by valegrajales** [PEM-Humboldt/core-geonetwork#4]
Ricardo y Edwing revisarán el funcionamiento de Geonetworl 3.2.1, durante la revisión deben incluir un issue por cada problema o mejora que deba realizarce.

**Comment by valegrajales** [comment]
Criterio de aceptación: Los administradores deberán tener conocimiento suficiente en la administración de Geonetwork 3.2.1, de modo que se puedan realizales manuales de usuario, administrador y catalogador. Deberán estar publicados tantos issues como mejoras y problemas detecten en 3.2.1

**Comment by erikasv** [comment]
No aplica.
