### ISSUE TITLE
Instalar contenedor para aplicación geonetwork 3.2.1

### ISSUE THREAD

**Issue by valegrajales** [PEM-Humboldt/core-geonetwork#6]
Es necesario habilitar la ejecución de apache tomcat con el war correspondiente a la aplicación geonetwork 3.2.1 sobre un contenedor de modo que podamos mapear el puerto de la aplicación al proxy del instituto es dirección: http://192.168.11.70:9000

**Comment by valegrajales** [comment]
Criterio de aceptación: Geonetwork 3.2.1 se puede consultar en la dirección http://192.168.11.70:9000/geonetwork

**Comment by rbastidas** [comment]
La aplicación se instala localmente en la siguiente URL:
http://192.168.205.12:9000/geonetwork/
Una vez se tenga un servidor con las características similares al Servidor de producción, se procederá a la configuración de GeoNetwork.

**Comment by erikasv** [comment]
El proceso se realizó con la versión 3.2.2
